version: '0.1-dev'
services:
    web:
        image: nginx:1.12.2-alpine
        restart: always
        ports:
            - "80:80"                                               # 自定义调整web服务端口
            - "443:443"                                             # 自定义调整web服务端口
        volumes:
            - /hosts:/hosts                                         # 自定义调整web路径
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf              # 自定义调整nginx配置
            - ./nginx/enable-php.conf:/etc/nginx/enable-php.conf
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf   # 自定义调整配置
        links:
            - php
    php:
        build: ./php
        restart: always
        volumes:
            - /hosts:/hosts                             # 自定义调整web路径
            - ./php/php.ini:/usr/local/etc/php/php.ini  # 自定义调整php配置
        links:
            - redis                                     # 本地调试不能采用127.0.0.1:6379 必须采用redis:6379，参考链接：https://stackoverflow.com/questions/42360356/docker-redis-connection-refused
            - mysql                                     # 本地调试不能采用127.0.0.1:3306 必须采用mysql:3306
    mysql:
        image: mysql:5.6.40
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=sql123                # 自定义调整mysql密码
        ports:
            - "3306:3306"                               # 自定义调整mysql端口
        volumes:
            - /data/mysql:/var/lib/mysql                # 自定义调整mysql数据路径
    redis:
        image: redis:3.2.11-alpine
        restart: always
        ports:
            - "6379:6379"                               # 自定义调整redis端口
        volumes:
            - /data/redis:/data                         # 自定义调整redis数据路径